# This workflow is designed to publish the react app when there is a commit on
# the main branch.

# Important note:
# On GitHub in the repository 'settings' in the section 'code and automation',
# 'pages' you need to manually click the button 'Build and deployment', 'Source'
# to enable GitHub Pages to be published via GitHub Actions!

name: Publish React App

on:
  push:
    branches:
      - main
  # This attribute allows to manually trigger the workflow from the
  # Actions tab from the GitHub website
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
 # Job that publishes the documentation to GitHub pages
  publish-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [21.x]
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: 'sofd-frontend'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './sofd-frontend/package-lock.json'
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install node dependencies
        run: npm ci --force
      - name: Update base url
        run: |
          echo "REACT_APP_HOME_PAGE='${{ github.event.repository.name }}/'" >> .env
        env:
          GITHUB_URL_MANUAL: ${{ steps.deployment.outputs.page_url }}
      - name: Build React App
        run: npm run build
      # Upload generated documentation and deploy it
      - uses: actions/upload-pages-artifact@v2
        with:
          path: './sofd-frontend/build'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
